### ISSUE TITLE
Questions regarding the contribution guidelines

### ISSUE THREAD

**Issue by davidarps** [fdalvi/NeuroX#15]
Dear NeuroX developers,
I am currently working on pull requests for two topics (control task, storing and processing activations with different dtypes).
I found your guidelines in the CONTRIBUTING.md quite useful! However, I was unsure at two points. I am working inside the `neurox-toolkit` conda env.

1. I ran `generate_docs.sh` to test if my documentation strings are rendered correctly. But the script crashed at the `make html` step saying that the `sphinx_book_theme` is not available. Installing the theme manually with pip did not help. 
2. I am not sure about the code style guidelines, which enforce the use of `black`. I tried the following snippet inside the neurox directory to format all code accordingly. but most of the previously existing .py files are changed by that. 

```
pip install black
black .
```

Do you have recommendations on these issues? Or are you still working on the contribution guidelines? I saw that they were changed quite recently.
Best,
David

**Comment by fdalvi** [comment]
Hello David,

Firstly, thanks for your interest in contributing to NeuroX! You have guessed correctly; the guidelines are still being worked on. I hope to get them to their final state in a couple days, so I'll keep this issue open and comment here when thats done. As for immediate suggestions:

- For docs, we are actually using `sphinx-apidoc`, so if you are familiar with its syntax, you can do your best effort to follow it and if we need to fix something later we can do so.
- for `black`, you can currently just run it on any new files thay you've created (by supplying the file as the argument instead of `.`

As for the tasks themselves, I would suggest making separate PRs for each task. I would also suggest starting a PR early when you are comfortable, instead of waiting to complete everything. This will help us guide you throughout the process!

Best,
Fahim

**Comment by davidarps** [comment]
Hello Fahim,
thanks, this helps a lot! I will open the PRs soon. 
Best,
David

**Comment by fdalvi** [comment]
Hi David,

Thanks so much for opening the PRs and apologies for the delay in getting back; I've updated the guidelines and the dev environment setup documentation, so you should be able to build and look at the documentation now. For now, I have _not_ formatted all of the repo code, because it will make updating your PRs a bit painful, so I'll do that once for the whole repo once we have your PRs in. So for the PRs themselves, just make sure the documentation looks alright and don't worry about running `black` or any formatting. We can discuss the specific PRs in their own space. Let me know if you have any problems with the guidelines in this issue, I'll keep it open for now.

Thanks again for your effort!

Fahim

**Comment by fdalvi** [comment]
Closing this as the repository is now updated + we have formatting checks for all future commits.
