### ISSUE TITLE
Error in linear_probe.train_linear_regression_probe()

### ISSUE THREAD

**Issue by Andrea-de-Varda** [fdalvi/NeuroX#18]
First of all, thank you for releasing such a great package! 

I just wanted to let you know that using the train_linear_regression_probe() you get a TypeError:

```
TypeError: _train_probe() got an unexpected keyword argument 'model_type'
```

This is because as an argument of _train_probe() you have model_type instead of task_type, but the argument is not one of the ones that is accepted by _train_probe()  - it's probably just a typo.

**Comment by fdalvi** [comment]
Hello @Andrea-de-Varda,

Thanks for the kind words and reporting the bug, it was indeed a typo. I've just pushed b95e10e that fixes this and adds some tests so we avoid this kind of issue in the future. We have actually not used the regression probe much, which is why the bug slipped through. If you notice any other issues, please feel free to reach out!

Best,
Fahim

**Comment by fdalvi** [comment]
I'll leave this issue open until we make a new release (should be in a few days as we are preparing a few other changes in other parts of the toolkit).

**Comment by fdalvi** [comment]
v1.0.9 is now out with this fix and a bunch of other improvements, thanks again for reporting!

**Comment by Andrea-de-Varda** [comment]
Thank you!
